baseURL = "https://kevingzhang.github.io"
languageCode = "en-us"
title = "Kevin Zhang - the Sweeper Monk"
theme = "air"
disqusShortname = "kevingzhang"
publishDir = "kevingzhang.github.io"
[[params.social]]
  name = "github"
  url = "https://github.com/vaga"
[params]
  author = "Sweeper Monk"
  description = "Bear with me as English is not my programming language"
  avatar = "https://avatars3.githubusercontent.com/u/1761809?s=400&v=4"
